### ISSUE TITLE
Improve HTML documentation

### ISSUE THREAD

**Issue by pulkomandy** [HaikuArchives/Dynamate#7]
The documentation is rather old-fashioned HTML. Update it to modern standards and try to make it look a bit nicer.

**Comment by DarkmatterVale** [comment]
@pulkomandy How creative can I get to make it look "nicer"? I have a couple ideas, but I would like to get a feel for what I can do and can't.

**Comment by pulkomandy** [comment]
I think anything that fits the game look is fine. Just try to keep it readable and make sure it works well in Web+, as this is what most people will use to read it.
What I have in mind for modernization is what I did on https://github.com/pulkomandy/critical-mass, but the design there has remained very simple.
